### PR TITLE
feature/modified-fields

### PR DESCRIPTION
**Pull request by novarac23**
## Scope

* Allow `update` action to store difference between old and new objects
* References issue https://github.com/soynatan/django-easy-audit/issues/24

## Why

Ability to see the `diff` or `delta` between old and new objects allows us to take logging to next level. For example somebody could implement "User X updated username from John to Johnny".

## ToDo

- [x] Add a new field to `CRUDEvent` model
- [x] Implement utilities for doing the deltas between two objects
- [x] Add `pre_save` signal in order to be able to store deltas
- [x] Modify `post_save` to not store objects if they are updated

### CODE REVIEW

**Comment by soynatan** [comment]
Hello, @novarac23. Thank you for this PR, it looks interesting. I changed the base, so as not to impact on master directly. I will be checking it out in the following days, as I'm a little busy at the moment. Thanks again!

**Comment by soynatan** [comment]
@novarac23: A detail that seems to be missing is to add the new field `changed_fields` to the `readonly_fields` list in admin.py. Can ỳou please do that and commit it?

_Note that it's not necessary to open a new PR, the commit should be added automatically to this one if you commit to your branch 'feature/modified-fields'_.

**Comment by novarac23** [comment]
@soynatan Thanks for taking the time to look into it!

I just pushed a change to add `changed_fields` to `readonly_fields`!

**Comment by kltdwrds** [comment]
@soynatan I was just looking for this functionality.  Thanks for the PR @novarac23!

**Comment by novarac23** [comment]
Just updated the PR to use arrays instead of tuples for storing an object diff. Reasoning behind that was that tuples were not JSON friendly and hard to consume. So I switched that to be an array of two elements 🤓

**Comment by soynatan** [comment]
Thank you, @novarac23. I merged it to branch feature/delta-update. Give me a few days to review it, and I'll merge it to master.

**Comment by novarac23** [comment]
@soynatan No problemo! Thanks!

**Pull request merged**
