### PR TITLE
Add new Django/Python versions

### LINKED ISSUE #182: Django 3.2 support
Thanks for this great package.

Django made 3.2 release a couple of days ago.

I wonder if there's any plan to upgrade django-easy-audit to be compatible with it?

Thanks!

### PR DESCRIPTION
**Pull request by serl**
Trying to fix #182 by reapplying #184 after #185.
As a bonus, I added also Python 3.9 and 3.10 to the test matrix,

### CODE REVIEW

**Comment by xjodoin** [comment]
Any update on the official 1.3.2 release?

**Comment by jheld** [comment]
I've been hoping for verification from the community. Have you been using the pre-release? If so, would you consider it stable for your use case?

**Comment by serl** [comment]
I've since changed my job so I'm not really using it anymore... I'm sorry I cannot help 😢

**Comment by xjodoin** [comment]
Yes, I did the validation with Django 3.2.10, and it works perfectly

**Comment by jheld** [comment]
just released `v1.3.2`, thank you!

**Pull request merged**
