### PR TITLE
Changed version to 1.1

### PR DESCRIPTION
**Pull request by funcho**
Version number changed to 1.1 for new release with latest bugfixes (https://github.com/soynatan/django-easy-audit/pull/58 and https://github.com/soynatan/django-easy-audit/pull/61)

### CODE REVIEW

**Comment by jheld** [comment]
cool!

We were able to successfully implement the user & content type db constraint removal (#71 ). If merged, perhaps it could go in 1.1 or 1.2?

#74 also slightly "fixed" it by ignoring the error when it occurs. We can get around this instead by using the previous CRUDEvent on the post_save, to emulate the change set. Not in this scope, but just stating an alternative.

**Comment by funcho** [comment]
We could create release 1.1 for now and when those changes are merged then version 1.2 would be created.

**Comment by funcho** [comment]
@jheld Is it posible to do that?

**Comment by jheld** [comment]
Yes, I think so.

I'll try to get my PR ready early next week.

I think I can merge this PR. If so, I'll check what's coming in since the last release and then pull the trigger. @soynatan we will also need a PyPI release.

**Comment by jheld** [comment]
Sorry that I haven't yet merged or made another PR, yet.

I'm also a bit hesitant to do the merge without having a PyPI release queued up shortly after. Everyone would have to put to github instead...not a great solution. Or make a custom `whl`, also not great.

**Pull request merged**
