### PR TITLE
Fix for Issue #62 use request.user in the request signal

### PR DESCRIPTION
**Pull request by chris-brent**

### CODE REVIEW

**Comment by jheld** [comment]
thank you. wow, didn't realize we weren't even trying to grab the user (if we could get it via the helper).

**Comment by jheld** [comment]
is it possible to add a test for this "new" behavior?

**Comment by chris-brent** [comment]
> is it possible to add a test for this "new" behavior?

Sure. You do have tests for the requests now? I only see these:
https://github.com/soynatan/django-easy-audit/blob/d772175500004322b096eb134367c5afdc5b06ef/easyaudit/tests/test_app/tests.py#L24

**Comment by jheld** [comment]
@chris-brent I'm unsure what tests are available/around.

But it would be great if you could add something that is able to test this new scenario.

**Comment by chrisbrent** [comment]
Hi I've left IONpath since last updating this so I don't have access to that fork anymore. I've opened a new PR with the same title and one updated test.

**Pull request closed without merging**
