### PR TITLE
Improved admin: Added filters and hyperlinks to admin; "Purge" action added to let superuser remove all rows from EasyAudit tables.

### PR DESCRIPTION
**Pull request by morlandi**
Just standard Django admin staff added for easier search and navigation of collected audit data,
plus "purge" action added to let superuser remove all rows from EasyAudit tables

### CODE REVIEW

**Comment by soynatan** [comment]
Wow, this is a great improvement to the admin! Before merging, I have a question: is there a reason why you are showing `object_json_repr_prettified` AND `object_json_repr` in the detail template? Seems to me that `object_json_repr_prettified` is enough.

Thank you for all the work!

**Comment by morlandi** [comment]
Hi, that was just in case someone would like to copy and paste the Json serialization in a compact form ... however, I do agree it's fully redundant; you might very well get rid of it

**Comment by morlandi** [comment]
Thank you @soynatan

**Comment by soynatan** [comment]
Thank _you_!

**Pull request merged**
