### PR TITLE
Fix #105

### LINKED ISSUE #105: Programming error when migrating to 1.1.1 on re- char field 0013, postgres
When I run `python manage.py migrate easyaudit` I get the following error:

`django.db.utils.ProgrammingError: relation "easyaudit_requestevent_url_37d1b8c4" already exists`

Full stack:

```
File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateTable: relation "easyaudit_requestevent_url_37d1b8c4" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/executor.py", line 269, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/migration.py", line 175, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 254, in database_backwards
    self.database_forwards(app_label, schema_editor, from_state, to_state)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    new_db_params, strict,
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 726, in _alter_field
    self.execute(self._create_index_sql(model, [new_field]))
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "easyaudit_requestevent_url_37d1b8c4" already exists
```

It has to do something with the back and forth from textfield to charfield in the newest version.

We use Django 2.2.6, and postgresql.

When reverting to migration 0008, I also get the same error.

Any idea why this is and how we can fix this?

When I reverted to easyaudit 1.1 without the bugfix, it worked fine again.

### PR DESCRIPTION
**Pull request by steverecio**
Edit migration 0013 to drop index on requestevent_url (fixes #105)

### CODE REVIEW

**Comment by jheld** [comment]
Does this permanently remove the index, or just in the middle of the migration process?

**Comment by steverecio** [comment]
This just drops the existing index during the migration (it gets re-added right after from the AlterField command).

```
project=# \d easyaudit_requestevent;
                                        Table "public.easyaudit_requestevent"
    Column    |           Type           | Collation | Nullable |                      Default
--------------+--------------------------+-----------+----------+----------------------------------------------------
 id           | integer                  |           | not null | nextval('easyaudit_requestevent_id_seq'::regclass)
 url          | character varying(254)   |           | not null |
 method       | character varying(20)    |           | not null |
 query_string | text                     |           |          |
 remote_ip    | character varying(50)    |           |          |
 datetime     | timestamp with time zone |           | not null |
 user_id      | integer                  |           |          |
Indexes:
    "easyaudit_requestevent_pkey" PRIMARY KEY, btree (id)
    "easyaudit_requestevent_method_83a0c884" btree (method)
    "easyaudit_requestevent_method_83a0c884_like" btree (method varchar_pattern_ops)
    "easyaudit_requestevent_remote_ip_d43af9b2" btree (remote_ip)
    "easyaudit_requestevent_remote_ip_d43af9b2_like" btree (remote_ip varchar_pattern_ops)
    "easyaudit_requestevent_url_37d1b8c4" btree (url)
    "easyaudit_requestevent_url_37d1b8c4_like" btree (url varchar_pattern_ops)
    "easyaudit_requestevent_user_id_da412f45" btree (user_id)
```

**Comment by jheld** [comment]
I wish that I'd seen this on MySQL. Maybe it could happen, or maybe it was just my environment.

I'll merge now and hopefully we never have to speak of this again!

**Comment by jheld** [comment]
OK, indeed the tests are failing for exactly this reason. I'm going to revert for now and we can merge this with a change, or re-merge and merge a downstream fix.

**Comment by steverecio** [comment]
Ok yeah sorry I didn't run the tests locally. I just created a new PR after fixing the test case regression.

**Pull request merged**
