### PR TITLE
Bugfix: RequestEvent url as charfield w/index.

### PR DESCRIPTION
**Pull request by jheld**
Undoes from issue #55 .

Caveat, for anyone that has run the migration, it seem safest to change the field type, and add the index.

For anyone that hasn't run that earlier migration, they should now be able to run it (just have no index), and then this new one will create the index. It's not as simple as I'd like, but I don't want to cause anyone runtime bugs during migration with SQL errors.

### CODE REVIEW

**Comment by jheld** [comment]
@jdkizer9 would this work for you?

**Comment by ahoneycutt** [comment]
@jheld Ran against backend testing ~1800 tests without incident. One thing to note is that I am not using the Request Events feature (ie `DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False`)

**Comment by jheld** [comment]
I haven run the custom branch locally (with request events on and on admin). Using MySQL. Migration ran. Django admin displays the rows, I can filter by user_id and by url prefix. Smoke tests are good!

**Comment by jheld** [comment]
@ahoneycutt  @jdkizer9  new release! 1.1.1rc1. Will go 1.1.1 official once its running good on someone's production. I'm 3 weeks out from getting it on production, but will have it on our dev env in a week.

**Comment by ahoneycutt** [comment]
Very excellent. I will see if we can target 1.1.1rc1 and give you any feedback. Thanks much!

**Pull request merged**
