### PR TITLE
ASGI RequestEvent support

### PR DESCRIPTION
**Pull request by jheld**
I have also created a test which utilizes ASGI (the view being called is synchronous, but that's fine!). Testing websocket at some point would be nice, as well as async views (websockets can be synchronous, which is a pattern django channels offers as a concrete solution). But yes, websockets likely would require django channels (not opposed to making it an extra install which is grabbed by the test runner), and that's outside the scope of this code change as that's not truly supported in django at this time (not natively).

### CODE REVIEW

**Comment by jheld** [comment]
This is designed to fix issue #81

**Comment by jheld** [comment]
@dopatraman would you willing to test this if you're still using the repo w/ASGI?

**Comment by jheld** [comment]
@CharleneCheung same question as above.

I am not entirely sure how to write tests for this yet but I do think it's likely going to work.

**Comment by CharleneCheung** [comment]
or maybe i just do a test later. thank you so much

Jason Held <notifications@github.com> 於 2020年7月25日 週六 上午5:21寫道：

**Comment by saengate** [comment]
@jheld @CharleneCheung Hello, I have an application that uses this and `manage runserver` throws the error in http while websocket works, in nginx http and websocket work perfectly. Disabling easyaudit is what worked for me to work with `manage.py runserver` and debug. I testing this branch with `pip install -e git+https://github.com/soynatan/django-easy-audit.git@feature/asgi-request-event#egg=django-easy-audit`. All work perfectly! I hope that you can mix this soon.

**Comment by jheld** [comment]
Oh that's great!

I am open to merging it without explicit unit tests, but I am a bit reluctant to do so unless we find that short term we don't know how to do it, haha.

But it was working for you, and that appears to give us the realistic confidence!

If you don't hear back within a week, please ping me here.

**Comment by jheld** [comment]
@saengate @CharleneCheung I've taken a swing at writing up a test. Turns out we didn't really have any tests (other than the skipped one which unfortunately had a bug around it so it had to be skipped since the code itself was commented out) for request event itself. We know have a WSGI and ASGI test to help keep this stable. I ran into a lot of confusion on the ASGI/asyncio story on how to do some of this. This is the first time I've really written any async code and even this wasn't that much. However, the tests do pass.

Also, I did have to update the easy audit middleware (well _had_ to is not accurate), so now it's no longer using the `MiddlewareMixin`. I did this partly because we don't want to (at this time) support ASGI so not using the mixin means that django will say "ok, you didn't say, therefore WSGI only", while the mixin had wsgi & asgi support, whoops! It does make the mixin a little more complex, but it may have been more complex with continuing to use the (soon to be deprecated) mixin because of how it logics on asgi and wsgi, and we need to manage the thread locals anyway.

For WSGI only, the code was fine as it was (adding a test was just a bonus). But for ASGI (regardless if the view is async or not), the middleware had to have a change no matter what. So, this is slightly more change than required, but I didn't do more than I felt was needed/warranted.

Would either of you be willing to test this? If so and it looks good, then I'm happy to merge it. If not, then I'll still merge -- the tests pass and we should be comfortable with the tests. That's also why this release is currently still an alpha as things can happen, this is when we find [the big] issues.

**Comment by saengate** [comment]
@jheld something in
[5438de3](https://github.com/soynatan/django-easy-audit/pull/147/commits/5438de357bcd69cc9bdefed8a5c090f8c477f563) has failed the application again, the same test I had performed before is now failing. If it helps you, i share my project, is open source [djfullapp](https://github.com/saengate/djfullapp) you can test this using `./manage.py runserver 0.0.0.0:7000` in the container and the port `7003` in localhost. `localhost:7003`

**Comment by jheld** [comment]
@saengate oh no! So, the only things that really changed were that i added a string `decode` line in the request started handler, and that the middleware now is more explicitly written, rather than relying on the mixin. Hmm.

**Comment by saengate** [comment]
@jheld try the previous commit and it also fails now, there is some forced change in this which is the cause of the error again probe `pip install -e git+https://github.com/soynatan/django-easy-audit.git@e7b80c3eb9f6ed75f28c922f5eee585d44dd6b24#egg=django-easy-audit`

**Comment by jheld** [comment]
@saengate so commit [e7b80](https://github.com/soynatan/django-easy-audit/pull/147/commits/e7b80c3eb9f6ed75f28c922f5eee585d44dd6b24) , the initial commit, is now not working? I didn't change that commit. I've only been building on top of it.

**Comment by jheld** [comment]
Also, do you have any errors/tracebacks which you can share?

Also, anytime we have to re-test this branch, we probably will want to first pip uninstall before installing again.

**Comment by saengate** [comment]
@jheld oh! My mistake was that I was not using the correct settings for the test. I testing the branch again and it's ok.
this time I ran with a
`pip install -e git+https://github.com/soynatan/django-easy-audit.git@feature/asgi-request-event#egg=django-easy-audit`
`./manage.py runserver 0.0.0.0:7000 --settings=config.debug.settings`
`pip freeze | grep django-easy-audit
-e git+https://github.com/soynatan/django-easy-audit.git@6c435ee01b1dd282e3bf9d20da55a73a5c15ec2a#egg=django_easy_audit`

**Comment by jheld** [comment]
@saengate no problem! Thank you for testing & providing feedback. Ok, I'll merge this and get it out in the `a4`.

**Comment by jheld** [comment]
OK, `1.3.0a4` is now on PyPI.

We'll give it a little bit of testing time, and then we'll officially release 1.3.0.

**Comment by jheld** [comment]
@saengate are you feeling confident with this version? I think this is the last change for the release. I'm happy to officially release `1.3.0` this week/end.

**Comment by saengate** [comment]
@jheld I had been a bit detached from this, but this week I will be using the project more thoroughly, if it has not been yet mixed and find any problem related this, i comment you.

**Comment by jheld** [comment]
I likely will cut the official release this weekend or early next week. Between the CharField object_id improvement, fixing a bug in a transaction on pre save (I think), and this, we're full with enhancements and we'll make any hotfixes an necessary. We've had this alpha out for several weeks so folks have had time to raise any concerns.

**Comment by jheld** [comment]
`1.3.0` is now on PyPI.

**Pull request merged**
