### PR TITLE
Customizable list filters for ModelAdmins

### PR DESCRIPTION
**Pull request by morlandi**
A possible solution for issue #52 (Add ability to hide filters in django admin)

### CODE REVIEW

**Comment by lorenzomorandini** [comment]
I find this quite useful, would be nice to see it accepted.

**Comment by soynatan** [comment]
This should be updated, since the code has changed quite a bit in the last year. I'm not sure weather we should prepare another PR, or update this one. A new PR sounds cleaner?

**Comment by morlandi** [comment]
Hello @soynatan, I'm still using an old version of django-easy-audit ... let me some time to update, then I'll send a brand new PR.
It's not a big deal, but since a user opened an issue, might be of some interest.

**Comment by soynatan** [comment]
> It's not a big deal, but since a user opened an issue, might be of some interest.

I like it! I think it could be useful.

> let me some time to update, then I'll send a brand new PR

Ok, so I'll close this PR. Thank you!

**Pull request closed without merging**
