### PR TITLE
Django4.0 compatibility

### PR DESCRIPTION
**Pull request by aymaneMx**
### What does this do?
- replace `force_text` with `force_str`
- replace `smart_text` with `smart_str`
- replace `from django.conf.urls import url` with `from django.urls import re_path`

closes: https://github.com/soynatan/django-easy-audit/issues/206

### CODE REVIEW

**Comment by Real-Gecko** [comment]
Can someone please arrange this? Really need Django upgrade.

**Comment by jheld** [comment]
I will try to review & merge this weekend.

**Comment by BartKalkman** [comment]
I there any update on this. We need the new version.

**Comment by jheld** [comment]
Sorry can you please add django 4.0 support into the .github/workflows/build.yml as that's where tests are officially run from?

**Comment by aymaneMx** [comment]
@jheld sure

**Comment by jheld** [comment]
@aymaneMx apologies but there is a bit more work to do on the test runner in github. Can you add similar exclude lines to what 3.2 has? I'll approve the test run now so we can easily see the failures but will wait to merge until those are configured differently.

**Comment by jheld** [comment]
please see pypi for version `1.3.3a1`. once we're happy with the stability, i'll cut the official release.

**Comment by jheld** [comment]
how's the feedback? are we safe to cut the official release?

**Comment by Real-Gecko** [comment]
I'm developing with Django 4 and Easy Audit since #213, haven't seen any errors so far. But thing to note I did not monitor Easy Audit closely too.

**Comment by mschoettle** [comment]
> how's the feedback? are we safe to cut the official release?

I've been running Django 4.0.2 and `1.3.3a6` for a couple weeks now locally. It is working fine but it is not heavy use currently (new project). I submitted #226 to fix the `default_app_config` deprecation warning that I keep getting, would be nice to get that into the next release.

**Comment by jheld** [comment]
release `1.3.3b1` is now PyPI and includes the fix on PR #226 

Happy to cut the official release with an approval on usage of that version.

**Pull request merged**
