### PR TITLE
Add configuration settings for admin search fields

### LINKED ISSUE #108: Support USERNAME_FIELD
Searching RequestEvents in the admin page breaks when using [USERNAME_FIELD](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD). 

`FieldError: Cannot resolve keyword 'username' into field. Choices are: datetime, id, method, query_string, remote_ip, url, user, user_id`

Maybe we can change any hardcoded 'username' references to settings.USERNAME_FIELD (mine is 'email' for instance).

### PR DESCRIPTION
**Pull request by steverecio**
Fixes #108

### CODE REVIEW

**Comment by jheld** [comment]
This looks really cool! Thank you.
Seems like it could make a 1.1.2 or 1.2 release!

We can plan for this once 1.1.1 release goes official and we see stability from it.

**Comment by jheld** [comment]
@steverecio I've just released 1.1.2rc1 which includes this support. Once we've seen some traction, I'll release 1.1.2 proper. Should be by sometime next week unless you or someone can verify the usage this week.

**Comment by steverecio** [comment]
@jheld What is the process for verifying usage? I'd love to get this release out and happy to help.

**Comment by jheld** [comment]
@steverecio Thanks for offering! We just started using it late last week in one of our pre-production environments and it works great so far. `1.1.2rc2` is on PyPI. It's probably ready as is, but please give it a go.

**Pull request merged**
